issue #99 feat: Create TeamPage
teamWaggle/Waggle-front pull request #126
Opened 2024-03-20 08:17 UTC by Hellol77

# 설명

- [https://github.com/teamWaggle/Waggle-front/issues/99](https://github.com/teamWaggle/Waggle-front/issues/99)

2024-03-20 08:49 UTC, sikkzz commented
97번 승인했으니 머지하고 pull 한번만 땡겨주세요 97번 브랜치 내용이 조금 있는 거 같아서요

2024-03-20 09:48 UTC, Hellol77 commented
> 97번 승인했으니 머지하고 pull 한번만 땡겨주세요 97번 브랜치 내용이 조금 있는 거 같아서요

넵넵

2024-03-20 09:49 UTC, sikkzz requested changes

2024-03-20 09:49 UTC, sikkzz commented on .gitignore
추가하신 이유가 있을까요? cache 파일들 프로젝트 단위 공통으로 관리하는게 아닌가 싶어서요

2024-03-20 09:49 UTC, sikkzz commented on src/components/Planning/Calendar/Calendar.tsx
postion util 2개 하나의 파일로 합쳐서 사용하는게 낫지 않을까요? generateCalendarPosition 같은 이름의 util파일 하나로요

2024-03-20 09:49 UTC, sikkzz commented on src/components/Planning/Calendar/CalendarCard/MoreModal/MoreButton.tsx
>  			<Box css={moreBoxStyle}>
<img width="448" alt="스크린샷 2024-03-20 오후 6 36 22" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/ab37b254-b354-42f1-bf3a-4f9292fd1193">

여기 스타일링에 fontsize랑 lineheight 없어도 되지 않나요?

2024-03-20 09:49 UTC, sikkzz commented on src/components/Planning/TeamCard/TeamCard.tsx
<img width="426" alt="스크린샷 2024-03-20 오후 6 41 19" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/7163ee3c-352c-4679-8d2d-69051d3e134e">

&nbsp 말고 gap주는게 좋을 거 같아요

2024-03-20 09:49 UTC, sikkzz commented on src/components/Team/TeamInfo/MemberSlider/MemberCard.tsx
> +import KebabMenu from "@/assets/svg/KebabMenu.svg?react";
Icon 붙여주세요 KebabMenuIcon 이렇게요

2024-03-20 09:49 UTC, sikkzz commented on src/components/Team/TeamInfo/ParticipationSlider/ParticipationSlider.tsx
memberSlider랑 공통화 시킬 수 있을 거 같아요

2024-03-20 09:49 UTC, sikkzz commented on src/hooks/useCalendar.ts
> +	const editCurrentMonth = (date: Date) => {
handleCurrentMonth가 좋지 않을까요?

2024-03-20 09:49 UTC, sikkzz commented on src/hooks/useHandleLinkWithDetectKeys.ts
이 로직은 다른곳에서 쓰이는게 없거나 앞으로도 추가적으로 공통화 시킬 게 없다면 내부에서만 쓰는게 낫지 않을까 싶기도 해요.
추후에 기능들이 더 추가되고 쓸 일이 있다면 상관 없기는 하지만요

2024-03-27 14:42 UTC, sikkzz commented
이거 build 돌려보시면 오류나는거 있는데 그부분들 수정 한번만 부탁드려요! build에러가 없어야 위에 보이시는 netlify에 x가 아니라 체크가 뜨거든요

2024-03-27 14:56 UTC, Hellol77 commented
> 이거 build 돌려보시면 오류나는거 있는데 그부분들 수정 한번만 부탁드려요! build에러가 없어야 위에 보이시는 netlify에 x가 아니라 체크가 뜨거든요

이게 디렉토리 구조가 다 바꿔서 이번만 작업한거랑 한꺼번에 다 같이 올릴게요

2024-03-27 15:28 UTC, sikkzz approved these changes

2024-03-28 03:50 UTC, merged