163 front task create create team page
teamWaggle/Waggle-front pull request #183
Opened 2024-04-04 05:50 UTC by Hellol77

# 설명

- [https://github.com/teamWaggle/Waggle-front/issues/163](https://github.com/teamWaggle/Waggle-front/issues/163)

- 지금 팀 생성 api 가 아직 작업중이신 것 같아서 일단은 api가 돌아가게만 처리했고 추후에 다시 변경하도록 할게요

2024-04-07 09:49 UTC, sikkzz requested changes

2024-04-07 09:49 UTC, sikkzz commented on src/api/interceptors.ts
> +	console.log(error);
console 문제 확인 하셨으면 삭제 해도 될 거 같아요

2024-04-07 09:49 UTC, sikkzz commented on src/components/CreateTeam/Main/Main.tsx
컴포넌트 Team directory로 옮기는게 좋지 않을까요 따로 있는거보다

2024-04-07 09:59 UTC, sikkzz requested changes

2024-04-07 09:59 UTC, sikkzz commented on src/components/CreateTeam/Main/Main.tsx
> +	const { convertToMediaUrl, uploadMedia } = useSingleImgUpload();
이거 rebase 땡기시면 파라미터 빈 객체로 바꾸셔야 할거에요

2024-04-07 10:13 UTC, sikkzz requested changes

2024-04-07 10:13 UTC, sikkzz commented on src/hooks/api/auth/useReissueToken.ts
> +	const { data } = useQuery({
suspesnse query로 바꿔주세요 그럼 아래 optional 연산자도 지울 수 있습니다

2024-04-07 10:13 UTC, sikkzz commented on src/hooks/api/auth/useReissueToken.ts
> +	const memberId = data?.result?.member.memberId || null;
위에 수정하면 옵셔널 삭제 가능하고 null 타입도 필요 없어요 그럼 타입에서 설정하신 member id 타입도 null 없어도 됩니다

2024-04-07 10:15 UTC, sikkzz requested changes

2024-04-07 10:15 UTC, sikkzz commented on src/hooks/api/auth/useReissueToken.ts
네이밍도 refresh가 낫지 않을까요

2024-04-07 10:36 UTC, Hellol77 commented on src/hooks/api/auth/useReissueToken.ts
네이밍이 refreshToken 이랑 관련있지 않는데 헷갈릴 것 같아서 다르게 네이밍해봤습니다

2024-04-07 10:39 UTC, Hellol77 commented on src/components/CreateTeam/Main/Main.tsx
Team page에 있는게 아니라 CreateTeam이라는 페이지가 따로 있어서 나눠놨습니다

2024-04-07 10:40 UTC, sikkzz commented on src/hooks/api/auth/useReissueToken.ts
나중에 제가 userurl도 같이 가져다 쓸 거 같은데 member 정보 관련 괜찮은 네이밍 없을까요
저는 멤버 정보 가져오는 query는 useMemberInfoQuery로 사용하고 있어요
폴더도 그럼 auth 쪽보다는 member 쪽이 좋지 않을까요?

2024-04-07 11:29 UTC, Hellol77 commented on src/hooks/api/auth/useReissueToken.ts
지금 다시 스웨거 보니까 이 api가 accessToken뿐만 아니라 refreshToken도 같이 재발급해주네요...?
차라리 토큰 재발급 받는 api랑 유저 memberId(유저 정보) 받는 api랑 나눠 달라고 할까요?

2024-04-07 11:33 UTC, sikkzz commented on src/hooks/api/auth/useReissueToken.ts
memberId랑 userURL만 받는거 하나 따로 있으면 될까요? 나머지 정보들은 변경 여지가 있긴 하니까요 userURL도 필요하긴 합니다

2024-04-07 11:41 UTC, Hellol77 commented on src/hooks/api/auth/useReissueToken.ts
그럼 토큰 재발급에서 member 객체만 따로 빼서 받아오는 api 하나 있으면 될것 같네요

2024-04-08 03:03 UTC, sikkzz approved these changes

2024-04-08 03:08 UTC, merged