187 front task feat pet info api
teamWaggle/Waggle-front pull request #188
Opened 2024-04-04 16:50 UTC by sikkzz

# 설명

- [https://github.com/teamWaggle/Waggle-front/issues/187](https://github.com/teamWaggle/Waggle-front/issues/187)
- 펫 정보 입력, 수정, 삭제 구현

2024-04-10 17:44 UTC, Hellol77 requested changes

2024-04-10 17:44 UTC, Hellol77 commented on src/components/common/WarningModal/DeleteWarningModal.tsx
> +			        : deletePetMutation;
음..차라리 함수들이나 문자열을 주입해주는건 어떨까요..?

2024-04-10 17:44 UTC, Hellol77 requested changes

2024-04-10 17:44 UTC, Hellol77 commented on src/components/common/WarningModal/DeleteWarningModal.tsx
> +				내용은 되돌릴 수 없습니다.
.

2024-04-11 10:09 UTC, sikkzz commented on src/components/common/WarningModal/DeleteWarningModal.tsx
> +			        : deletePetMutation;
타겟을 prop으로 받고 해당 게시물에 맞는 mutation 함수와 텍스트를 렌더링하는건데 이렇게 안하려면 텍스트는 props로 받으면 되는데 각 해당되는 mutation을 props로 넘겨줘야 합니다.

mutation을 props로 넘기는건 좀 별로지 않을까요? 다른 방법은 해당 로직을 util로 빼서 사용하는 방법이 있긴 합니다

2024-04-11 11:32 UTC, Hellol77 commented on src/components/common/WarningModal/DeleteWarningModal.tsx
> +			        : deletePetMutation;
제 생각은 props로 넘기는게 더 좋다고 생각한게 만약 여기에 기능이 추가 된다고 하면 조건문을 mutate 부분도 수정해야하고 문자열 부분도 추가해줘야 하죠. 물론 저희 프로젝트 특성상 이 부분에서 기능이 추가될 것 같지는 않지만 props로 전달하면 기능추가도 자유롭고 더 이상이 컴포넌트는 신경 안써도 되지 않을까요..? 그리고 컴포넌트 의존성이 너무 많아보여서 줄여야할 필요가 있지 않나 싶어서요

2024-04-11 12:19 UTC, Hellol77 approved these changes
👍

2024-04-11 12:19 UTC, merged