228 front task planning team page connect api
teamWaggle/Waggle-front pull request #245
Opened 2024-04-22 12:47 UTC by Hellol77

# 설명

- [https://github.com/teamWaggle/Waggle-front/issues/228](https://github.com/teamWaggle/Waggle-front/issues/228)
- 일정 수정, 일정 검색, 일정 취소, 일정 삭제, 팀 참여 수락 및 거절
- 일정 수정시 시작일이 오늘이 이전이면 수정이 안되는 현상이 있는데요 일단 이번 머지하고 디자인시스템으로 전부 다 옮기고 진행 할까 해요
- setQueriesData를 사용중인데 일정이 적으면 성능 문제는 없지만 많아지면 성능 문제가 있을 수 있습니다. 이것도 일단 상황을 보고 진행하도록 할게요

2024-04-22 14:15 UTC, sikkzz commented
<img width="719" alt="스크린샷 2024-04-22 오후 11 14 32" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/be9b3b40-c9ff-496c-af96-555abe3d8ca5">

최대 인원수 표기, 팀 대표 이미지 적용 필요하겠네요

2024-04-22 14:16 UTC, sikkzz commented
<img width="1251" alt="스크린샷 2024-04-22 오후 11 15 53" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/b4ec7d03-7587-4aab-93ad-08eac373c1ed">

내 팀 목록 아래쪽으로는 팀 전체 목록이 떠야하지 않나요? 이것도 아직 안뜨는거 같아요

2024-04-22 14:17 UTC, sikkzz commented
<img width="1311" alt="스크린샷 2024-04-22 오후 11 16 43" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/11fe3701-3650-4df1-9c73-c5d9f8ad95e7">

팀이 현재 4개인데 4개일때는 화살표 렌더링이 안되는게 맞는거 같아요 5개부터 작동해야하니까요

2024-04-22 14:21 UTC, sikkzz commented
<img width="1027" alt="스크린샷 2024-04-22 오후 11 20 17" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/4186d955-c47c-45f7-9d0a-908568383bb3">

스크롤 포커스가 일정 모달에 가있을 경우 바깥쪽 화면은 스크롤이 안되는게 맞는 거 같아요
overscrollBehavior: "contain", 속성 사용하면 스크롤 영역 관리할 수 있습니다.

2024-04-22 14:22 UTC, sikkzz commented
<img width="1716" alt="스크린샷 2024-04-22 오후 11 21 38" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/a568b71c-d77a-41b8-ba11-99568a6d9321">

팀페이지 컬러들 팀 대표 컬러로 바꿔줘야 겠네요

2024-04-22 14:23 UTC, sikkzz commented
<img width="532" alt="스크린샷 2024-04-22 오후 11 22 59" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/0f127472-8022-4c88-9c13-380ed3447584">

팀 이미지 설정해주세요

가입 신청이 없으면 새로운 가입 신청 텍스트도 렌더링 안시켜도 될 거 같지 않나요?

2024-04-22 14:25 UTC, sikkzz commented
<img width="732" alt="스크린샷 2024-04-22 오후 11 24 51" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/0a160c09-bfb1-4957-bc1b-53d0fbb43b25">

default 값을 오늘 날짜로 해놓는게 좋을 거 같아요

2024-04-22 14:26 UTC, sikkzz commented
<img width="305" alt="스크린샷 2024-04-22 오후 11 26 08" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/d22bb333-379d-4f40-b00a-20a22c30fa90">

달력 버튼 클릭 시 key값 에러뜨네요

2024-04-22 14:28 UTC, sikkzz commented
<img width="524" alt="스크린샷 2024-04-22 오후 11 27 52" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/c0720f28-7dd2-4cbb-92d8-d8ff3f91ed85">

팀 이름 연결시켜야겠네요

2024-04-22 14:31 UTC, sikkzz commented
<img width="264" alt="스크린샷 2024-04-22 오후 11 30 30" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/ba712f11-71d6-430b-ac08-e26f9c9d322e">

예정도 다른 컬러가 좋지 않을까요?

2024-04-22 14:34 UTC, sikkzz commented
<img width="671" alt="스크린샷 2024-04-22 오후 11 32 58" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/08db58c0-14c5-4e12-8d68-2d1df00877c1">

<img width="406" alt="스크린샷 2024-04-22 오후 11 34 15" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/bca2abda-9c61-4e94-ad38-c10133e35cc4">

일정 추가할때 달력 시간도 현재 시간을 default로 해놓는게 좋을 거 같아요.

현재 시간 이전 시간들을 일정으로 등록하는건 validate가 잘 되어있는데 그냥 일정 추가 킨 상태로 시간 수정 안하고 일정 등록하면 validate 작동 안하고 등록됩니다.

두번쨰 사진 보시면 현재 시간 4월 22일 11:34분인데 4월 22일 오전 12시~12시 15분 일정이 등록됩니다

2024-04-22 14:35 UTC, sikkzz commented
<img width="1444" alt="스크린샷 2024-04-22 오후 11 35 30" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/130a16f7-80d7-4a7b-a688-c18156c24f33">

페이지 하단 여백이 필요할 거 같아요 시안 보면 112px 떨어져있긴 합니다

2024-04-22 14:36 UTC, sikkzz commented
<img width="1265" alt="스크린샷 2024-04-22 오후 11 36 10" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/c505e885-1e81-4954-a1f2-8de3c2b4fef5">

여기도 team 목록 추가 이후에 하단 여백 넣어줘야겠네요

2024-04-22 14:37 UTC, sikkzz commented
<img width="451" alt="스크린샷 2024-04-22 오후 11 37 29" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/f7ebbf2b-0e93-4120-b76e-0001997dd500">

여기도 신나는 강아지 유치원 -> 팀 이름 넣어줘야겠네요

2024-04-22 14:42 UTC, sikkzz commented
<img width="729" alt="스크린샷 2024-04-22 오후 11 41 26" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/018175fe-f718-42be-b83a-bcc60a3d9563">

일정 수정 시 버튼 텍스트도 일정 수정으로 바꿔야 겠네요. 그리고 일정 수정 submit하면 일정은 정상적으로 수정되는데 일정 수정 모달이 안꺼집니다

2024-04-22 14:43 UTC, sikkzz commented
<img width="323" alt="스크린샷 2024-04-22 오후 11 43 02" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/8070d759-dd36-4a9e-990b-b12d835e2f4f">

일정 클릭 outsideclick이 이상한거 같아요. 일정 막대 클릭시 껏다 켜졌다 해야하는데 한번 켜지면 다시 눌러도 안꺼집니다

2024-04-22 14:53 UTC, sikkzz requested changes

2024-04-22 14:53 UTC, sikkzz commented on packages/waggle-service/src/main.tsx
> +          <ThemeProvider theme={Theme}>
Waggle Provider로 변경하면 아래 global style 다 지울 수 있습니다

2024-04-22 14:53 UTC, sikkzz commented on packages/waggle-service/src/main.tsx
> +            <Suspense fallback={<div></div>}>
이건 지워주세요 제쪽 브랜치에서도 지웠는데 글로벌하게 suspense 적용시켜놓는건 안좋은 선택 같아요

2024-04-22 14:53 UTC, sikkzz commented on packages/waggle-service/src/hooks/api/team/useDeleteTeamMember.ts
> +      console.log(result);
console 제거

2024-04-22 14:53 UTC, sikkzz commented on packages/waggle-service/src/components/common/OptionModal/OptionModal.tsx
> +    <div ref={modalRef} css={optionModalList} onClick={handleOptionModalClick}>
인라인에서 그냥 () => closeModal()로 넘겨줘도 괜찮지 않나요? 함수를 한번 더 선언한 특별한 이유가 있나 싶어서요

2024-04-22 14:54 UTC, sikkzz commented
팀원 관련 기능들은 팀 리스트 접근이 현재 불가능해서 테스트 못해봤습니다. 팀 리스트를 추가해야 팀에 신청해보고 팀원 관리 기능 테스트해볼 수 있을 거 같아요

2024-04-22 15:02 UTC, Hellol77 commented
> <img alt="스크린샷 2024-04-22 오후 11 14 32" width="719" src="https://private-user-images.githubusercontent.com/100590110/324493446-be9b3b40-c9ff-496c-af96-555abe3d8ca5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3OTgwNTAsIm5iZiI6MTcxMzc5Nzc1MCwicGF0aCI6Ii8xMDA1OTAxMTAvMzI0NDkzNDQ2LWJlOWIzYjQwLWM5ZmYtNDk2Yy1hZjk2LTU1NWFiZTNkOGNhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQxNDU1NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTJhMDc1MDQ2ZjQzODVjZjAzYjNjMzk2M2RiODUwYWY1ZTk1MDBkMGRkYzc1MGU5NmIxZGYzMmQzZmVlMDFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vt5ehzb4BHMjPQQnyd72DxPw4GPFajHWK4nyQq81p2g">
> 최대 인원수 표기, 팀 대표 이미지 적용 필요하겠네요

Planning 페이지는 검색 api 만들어질때 다같이 손보려고 합니다
Planning 페이지는 추후 디자인 시스템으로 바꾼뒤 손볼게요

2024-04-22 15:04 UTC, Hellol77 commented
> <img alt="스크린샷 2024-04-22 오후 11 32 58" width="671" src="https://private-user-images.githubusercontent.com/100590110/324499980-08db58c0-14c5-4e12-8d68-2d1df00877c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3OTgwNTAsIm5iZiI6MTcxMzc5Nzc1MCwicGF0aCI6Ii8xMDA1OTAxMTAvMzI0NDk5OTgwLTA4ZGI1OGMwLTE0YzUtNGUxMi04ZDY4LTJkMWRmMDA4NzdjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQxNDU1NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDA0ZWQxNzg4MTNkN2MxMGJjZjg0YTBhNDIwZjBkYjIzOTI1NjQ0ZTM3OGIxMzc3YmM4NWIwMTYxY2QyZjJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.shuYiiWHQ9aPs6rj_Us5wYsVgcZkm1dYE-5SDfQ53fY"> <img alt="스크린샷 2024-04-22 오후 11 34 15" width="406" src="https://private-user-images.githubusercontent.com/100590110/324500435-bca2abda-9c61-4e94-ad38-c10133e35cc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3OTgwNTAsIm5iZiI6MTcxMzc5Nzc1MCwicGF0aCI6Ii8xMDA1OTAxMTAvMzI0NTAwNDM1LWJjYTJhYmRhLTljNjEtNGU5NC1hZDM4LWMxMDEzM2UzNWNjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQxNDU1NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDNiM2Y5MGJiZjUxYjQ1MTAwM2Y3NDZjZTg0NGIzNjQxYzk0YThhYzEwZjlkY2VmYmFiMGQzZTlhM2QyMzEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IjBtTXJlM1gEFUctRju5xftCPmEwmzoehZdrT1KT21I">
> 일정 추가할때 달력 시간도 현재 시간을 default로 해놓는게 좋을 거 같아요.
> 
> 현재 시간 이전 시간들을 일정으로 등록하는건 validate가 잘 되어있는데 그냥 일정 추가 킨 상태로 시간 수정 안하고 일정 등록하면 validate 작동 안하고 등록됩니다.
> 
> 두번쨰 사진 보시면 현재 시간 4월 22일 11:34분인데 4월 22일 오전 12시~12시 15분 일정이 등록됩니다

이거 format 고치는 거 깜빡했네요

2024-04-22 15:29 UTC, Hellol77 commented
> <img alt="스크린샷 2024-04-22 오후 11 24 51" width="732" src="https://private-user-images.githubusercontent.com/100590110/324497026-0a160c09-bfb1-4957-bc1b-53d0fbb43b25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3OTk2NzQsIm5iZiI6MTcxMzc5OTM3NCwicGF0aCI6Ii8xMDA1OTAxMTAvMzI0NDk3MDI2LTBhMTYwYzA5LWJmYjEtNDk1Ny1iYzFiLTUzZDBmYmI0M2IyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQxNTIyNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjNlMWQ4NDkwMTZhN2JiMmE4N2VmMzU3NGJlYjFjMDM5N2JlYzQ1MzI1YjBmOWQ1NDM2MzczY2QyZmRmODhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TUSYh5wLm34U8R0dAIDQki4vi6XLjcYz31cdCczGIY8">
> default 값을 오늘 날짜로 해놓는게 좋을 거 같아요. 초기화 했을때도 오늘 날짜가 좋지 않을까요?

검색을 안했을때 오늘의 날짜의 일정만 가져오는게 아니라서 혹시나 혼란을 주지 않을까라는 생각에 이렇게 만들었어요. 회의때 다시 한번 봐야겠네요

2024-04-22 15:32 UTC, Hellol77 commented on packages/waggle-service/src/main.tsx
> +            <Suspense fallback={<div></div>}>
이건 사실.. 하나하나씩 suspense 하기 귀찮아서 넣어놨어요 디자인 시스템으로 변경할때 지우겠습니다. 사실 제일 가까운 상위 Suspense의 fallback 이 보여줘서 큰 이슈는 아닐 것 같아요

2024-04-22 15:39 UTC, Hellol77 commented on packages/waggle-service/src/components/common/OptionModal/OptionModal.tsx
> +    <div ref={modalRef} css={optionModalList} onClick={handleOptionModalClick}>
이건 사실 습관이긴 한데요. 이렇게 하는 이유는 혹여나 나중에 추가될 로직이 있다면 바로 추가해줄 수 있기 때문에 이렇게 처리를 해왔습니다.

2024-04-22 15:39 UTC, Hellol77 commented on packages/waggle-service/src/main.tsx
> +          <ThemeProvider theme={Theme}>
제가 이번에 Theme에 추가한 색이 있어서 임시로 써놨습니다. 디자인 시스템에는 색을 추가를 안해놔서요. 디자인 시스템으로 변경할때 같이 수정할게요

2024-04-22 15:45 UTC, sikkzz commented on packages/waggle-service/src/main.tsx
> +            <Suspense fallback={<div></div>}>
suspense 적용시키면서 로딩 UI가 특정 컴포넌트에서 처리가 안되어 있어도 여기 이 코드때문에 오류가 안나고 그냥 동작하니까 문제일 거 같아요

로딩 UI들은 당연시하게 추가해주는게 UX에 좋으니까요 이미 제 브랜치에서 지워진 상태라 여기서도 지우는게 좋을 거 같아요.

디자인 시스템 변경하시는게 다른 브랜치에서 이뤄질 예정이면 지워주세요.  해당 브랜치에서 수정하실꺼면 상관없습니다

2024-04-22 15:47 UTC, sikkzz commented on packages/waggle-service/src/components/common/OptionModal/OptionModal.tsx
> +    <div ref={modalRef} css={optionModalList} onClick={handleOptionModalClick}>
코드 라인이 늘어나는걸 고려하면 인라인으로 처리해주는게 좋은 거 같아요. 물론 해봤자 1~2줄 차이긴 하지만 적은게 당연히 좋으니까요.

추가적인 로직이 들어가야 하면 함수로 냅두고 아니면 인라인으로 넣어주는게 좋을 거 같습니다.

2024-04-22 17:08 UTC, Hellol77 commented on packages/waggle-service/src/main.tsx
> +            <Suspense fallback={<div></div>}>
사실 정확히 말하자면 suspense가 없어 로딩 ui가 특정 컴포넌트에 처리가 안되어 있어도 useSuspenseQuery에서는 에러를 발생하지 않는걸로 알고있어요.
그리고 로딩UI 예를 들어 스켈레톤 같은게 당연시 하다는 것도 사용자 경험을 생각한다면 좋은 생각이 아닐 수도 있습니다.
인터넷이 빠른 사용자들은 오히려 덜그럭 거리는 화면을 보게 될 수도 있어서요
https://tech.kakaopay.com/post/skeleton-ui-idea/
저도 요 글 보고 안거라 참고하시면 좋을 것 같습니다

2024-04-22 17:41 UTC, sikkzz commented on packages/waggle-service/src/main.tsx
> +            <Suspense fallback={<div></div>}>
정보 감사합니다.

suspense query를 사용할떄 에러가 났던 적이 있었는데 에러를 발생시키지 않는다는건 몰랐네요. 다만 빈 div로 fallback을 처리해놓는다 하더라도 빈 화면으로 인해 흰색 화면이 한번 렌더링되는 깜빡임은 사용자가 겪을 수 밖에 없는 부분 아닌가요

인터넷이 빠르다는 가정하에서는 당연하지만 인터넷이 갑작스럽게 느려지는 경우 또한 고려해야하는거 같구요. 해당 포스팅에서는 서비스를 운영하면서 네트워크 응답 시간을 체크해보고 일정 시간 이후에 렌더링 시켜주는 방식을 채택하고 있는데 현재 상태에서는 저희는 당장 얼마나 지연시킬지 적용시키기는 어려울 거 같고요

suspense 처리를 안할거면 모르겠는데 그게 아니기에 로딩 ui는 사용해야하지 않나 싶어요. 포스팅 처럼 지연시켜서 페이지를 로딩시켜주는 방법을 이후에 적용시키는거도 고려해봐야겠네요

2024-04-22 23:29 UTC, Hellol77 commented on packages/waggle-service/src/main.tsx
> +            <Suspense fallback={<div></div>}>
빈 회면(아무 suspense 처리를 하지 않은 상태 혹은 빈 div로 처리되어있는 상태)이 지나가는 것과 회색 스켈레톤 로딩이 눈앞에 지나기는건 상당히 차이가 있디고 봅니다 빈화면은 전체화면이 아니라 api가 불려지는 곳에만 나오기 때문에 덜그럭 거리는 화면은 스켈레톤 ui를 적용한 화면만 나타날거에요 따라서 제안하는건 뭐 추후에 게시물에서 제시한 방법을 사용한 방법을 사용하면 좋겠지만 일단은 모든 곳에 suspense를 빈 div로 걸어두고 오래걸릴것 같은 부분만 따로 suspense작업을 해주는게 어떨까싶어요 스토리 게시글 불러오는건 오래걸릴수 있기때문에 스켈레톤 ui를 지금 처럼 설정해주고 제가 하고 있는 팀 참가 요청리스트 처럼 별로 걸리지 않는 부분은 전역처리되어 있는 빈div로 사용하는 거죠 저도 일정 기간 검색은 오래 걸릴수 있는 작업이기 때문에 스피너ui를 쓰고 있구요

2024-04-23 11:01 UTC, sikkzz commented on packages/waggle-service/src/main.tsx
> +            <Suspense fallback={<div></div>}>
말씀하시는 덜그럭거림이 한번 깜빡하면서 렌더링 되는걸 말씀하시는게 아닌가요? skeleton ui를 쓰는거랑 빈 화면 div를 쓰는거랑 상당한 차이가 있다는 부분이 이해가 안가네요

제 브랜치 skeleton 적용해놓은 부분 보시면 알겠지만 api로 로딩처리가 되는 부분들 제외하고는 일반 화면이랑 동일하게 렌더링됩니다. api 요청되는곳만 빈화면이 렌더링되는거나 스켈레톤 ui가 렌더링되는거나 차이가 없을텐데 어떤 큰 차이가 있다고 말씀하시는건지 모르겠어요

2024-04-23 14:40 UTC, Hellol77 commented on packages/waggle-service/src/main.tsx
> +            <Suspense fallback={<div></div>}>
덜그럭 거림이라는 것은 순전히 배경과 다른 회색 스켈레톤 ui 때문에 이루어지는 현상입니다. 빈 div를 쓰면 덜그럭 거리는 현상은 일어나지 않는 거죠. 카카오 게시물을 보시면 지연시간이 짧은 시간, 긴 시간에 회색 스켈레톤이 보여지는 모습을 비교 하고 있는데요. 긴 시간이 걸리는쪽은 지연시간이 길어 스켈레톤 인지 사용자가 인식 할 수 있어 적합한 ui이지만 지연시간이 짧은 쪽은 회색 스켈레톤인지 인식할 수 없을 정도로 순식간에 지나가 화면이 깨진 느낌 즉 덜그럭 거리는 현상일어나 부자연스러운 ui가 되는 거죠
따라서 길게 걸릴 것 같은 api 요청에만 스켈레톤을 넣고 나머지는 빈 suspense를 설정하면 이러한 모습을 조금이라도 해결가능하고 로딩 ui를 신경쓰는 비용이 줄것 같습니다. 
제가 위에서 잘못 생각한 것이 전역으로 suspense를 처리했을때 api 마다 컴포넌트를 분리 시켜주지 않았다면 waterfall 현상이 일어난다고 해서 전역으로 suspense를 처리해주는 건 현재 api마다 컴포넌트로 분리해주는 리펙토링이 진행되지 않는 이상 어려울것 같네요. 나중에는 api 마다 컴포넌트 분리를 해주고 suspense를 ux 전략에 따라 병렬로 처리 할지 먼저 완료된 요청부터 보여줄지 선택해야 될 것 같습니다.

2024-04-29 15:52 UTC, sikkzz approved these changes

2024-04-29 15:53 UTC, merged