244 front task refactor modal component
teamWaggle/Waggle-front pull request #246
Opened 2024-04-22 13:59 UTC by sikkzz

# 설명

- [https://github.com/teamWaggle/Waggle-front/issues/244](https://github.com/teamWaggle/Waggle-front/issues/244)
- 모달 로직 수정

useModal이랑 Modal root 사용하던 modal recoil 로직 없이 각각의 모달 open, close hook으로 사용할 수 있게 수정했습니다.
planning 파트 모달들은 아직 수정 안하고 냅뒀습니다.

2024-04-22 15:22 UTC, Hellol77 requested changes

2024-04-22 15:22 UTC, Hellol77 commented on packages/waggle-design-system/src/components/Modal/Modal.tsx
모달을 새로 만드신 이유가 있으실까요?

2024-04-22 15:22 UTC, Hellol77 commented on packages/waggle-design-system/src/components/Modal/Modal.tsx
> +          </dialog>
dialog 태그와 createPortal과 동시에 사용하신 이유가 궁금합니다

2024-04-22 15:22 UTC, Hellol77 commented on packages/waggle-service/src/components/Login/Login.tsx
> +  } = useOverlay();
이렇게 관리하면 만약 모달갯수에 비례해서 useOverlay를 써줘야 한다는 것과 항상 부모 컴포넌트에서 useOverlay를 써서 close를 항상 modal에 props로 넘겨줘야 한다는 점이 있습니다.

2024-04-22 15:37 UTC, sikkzz commented on packages/waggle-design-system/src/components/Modal/Modal.tsx
기존 모달 로직의 경우 recoil과 useModal hook에서 모달 state들을 관리해줬는데 현재 동현님 브랜치쪽 코드 보시면 하나의 통일된 로직으로 사용하는게 아닌 상황에 맞춰 로직들을 조금씩 변경하고 recoil state들도 변화를 줘서 사용하고 있는거로 봤습니다.

그리고 제가 개발하는쪽에서 모달 위에 모달이 겹치는 형태가 있는데 변경 전 로직에서는 modal.closeModal로 모든 모달을 끄거나 selectCloseModal로 특정 모달을 끄는 두가지 로직을 사용했습니다.

위 로직에서 문제점은 2개이상의 모달이 열려있을 때 backdrop 클릭하거나 esc를 누르면 특정 모달만 꺼져야 하는데 모달별로 각각 관리하는게 아니다 보니 하나만 끄는게 불가능했습니다.

각각의 모달 상태는 개별로 관리되어야 하니까 통일된 로직인 custom hook useOverlay와 commom modal 컴포넌트를 사용해서 모달 로직을 통일시키고  켜지고 꺼지는 상태 또한 개별로 관리할 수 있게 변경하려고 만들었습니다

이러면 recoil state도 사용할 필요 없고 모달을 키고 끄는 hook과 모달 최상위 컴포넌트는 통일해서 사용할 수 있고 일부 기능 실행시 모달이 꺼지고 켜지는 특이 상황들도 해당 컴포넌트에서만 관리해주면 될 거 같아서 로직을 변경했습니다.

정리하면 로직 통일, 컴포넌트 독립성 유지를 위해서 변경했다고 보시면 될 거 같네요

2024-04-22 15:38 UTC, sikkzz commented on packages/waggle-service/src/components/Login/Login.tsx
> +  } = useOverlay();
props로 넘겨줘야하는건 단점이 맞지만 해당 모달의 open과 close의 영향은 해당 컴포넌트와 그 아래 자식 컴포넌트에서만 관리 및 변경 되어야한다는 점을 생각해서 해당 로직으로 변경하기도 했습니다.

2024-04-22 15:42 UTC, sikkzz commented on packages/waggle-design-system/src/components/Modal/Modal.tsx
> +          </dialog>
isOpen이 true일때만 모달이 렌더링 되어야 한다 생각하고 넣어줬는데 isOpen 조건이 없어도 정상 작동하긴 하네요 없어도 될 거 같아요

2024-04-24 10:29 UTC, Hellol77 approved these changes

2024-04-28 14:45 UTC, merged