265 front task feat sort api
teamWaggle/Waggle-front pull request #271
Opened 2024-05-02 15:04 UTC by sikkzz

# 설명

- [https://github.com/teamWaggle/Waggle-front/issues/265](https://github.com/teamWaggle/Waggle-front/issues/265)
- story, siren, Q&A 정렬 구현
- siren category 정렬은 추후 논의 후 재구현

2024-05-03 03:38 UTC, Hellol77 requested changes

2024-05-03 03:38 UTC, Hellol77 commented on packages/waggle-service/src/components/Story/StoryMain/StoryMain.tsx
>              <RetryErrorBoundary>
자식 컴포넌트가 api호출을 안하기 때문에 작동하지 않을것 같은데 여기서 에러바운더리 작동하나요?

2024-05-03 06:58 UTC, sikkzz commented on packages/waggle-service/src/components/Story/StoryMain/StoryMain.tsx
>              <RetryErrorBoundary>
그러네요 우선 상위로 올려놨습니다

2024-05-09 03:27 UTC, Hellol77 approved these changes

2024-05-09 03:40 UTC, merged