276 front task add api in detail schedule
teamWaggle/Waggle-front pull request #288
Opened 2024-05-13 15:22 UTC by Hellol77

# 설명

- [https://github.com/teamWaggle/Waggle-front/issues/276](https://github.com/teamWaggle/Waggle-front/issues/276)

2024-05-13 18:42 UTC, sikkzz requested changes

2024-05-13 18:42 UTC, sikkzz commented on packages/waggle-service/src/api/comment/postComment.ts
> +    CommentApiRequestType,
CommentPropsType 쓰시면 될 거 같은데요?

2024-05-13 18:42 UTC, sikkzz commented on packages/waggle-service/src/api/comment/putComment.ts
> +  return authorizedAxiosInstance.put<CommentApiRequestType, AxiosResponse<CommonResponseType>>(
여기도 EditCommentPropsType 쓰시면 될 거 같네요

2024-05-13 18:42 UTC, sikkzz commented on packages/waggle-service/src/api/interceptors.ts
> +  console.log(error);
확인용으로 계속 냅둬야 하는 콘솔일까요?

2024-05-13 18:42 UTC, sikkzz commented on packages/waggle-service/src/components/Planning/TeamCard/TeamCard.tsx
<img width="355" alt="스크린샷 2024-05-14 오전 3 05 12" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/58be3a70-6ff5-4057-a793-608e79dd66d3">

팀 생성시 이미지가 제대로 안나오네요

2024-05-13 18:42 UTC, sikkzz commented on packages/waggle-service/src/components/Planning/TeamCard/TeamCard.tsx
<img width="391" alt="스크린샷 2024-05-14 오전 3 06 35" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/22c71aa1-1114-4af0-8764-ce5c5714c47d">

medium은 default라 없어도 됩니다

2024-05-13 18:42 UTC, sikkzz commented on packages/waggle-service/src/components/Planning/TeamCard/TeamCard.tsx
<img width="526" alt="스크린샷 2024-05-14 오전 3 08 08" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/3a019b50-b4eb-4cff-8954-e18593a574da">

팀 페이지 들어가서도 이미지가 제대로 안뜹니다

2024-05-13 18:42 UTC, sikkzz commented on packages/waggle-service/src/components/Planning/TeamCard/TeamCard.tsx
<img width="289" alt="스크린샷 2024-05-14 오전 3 10 01" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/67cfd517-4901-48b1-a7cc-88954c9afbe8">

팀 최대 인원수 여기도 맞춰줘야 할 거 같아요

2024-05-13 18:42 UTC, sikkzz commented on packages/waggle-service/src/components/Planning/TeamCard/TeamCard.tsx
<img width="244" alt="스크린샷 2024-05-14 오전 3 11 18" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/70a39a34-ec8e-44ca-b0be-5de251e76f84">

여기 시안 보면 팀원 관련 버튼이 있는데 안들어갔네요. 그리고 여기 팀원 목록에 본인도 포함되는건지 논의가 필요할 거 같아요

![스크린샷 2024-05-14 오전 3 11 46](https://github.com/teamWaggle/Waggle-front/assets/100590110/44cda696-0009-419d-8ef7-31b98a2a27c4)

2024-05-13 18:42 UTC, sikkzz commented on packages/waggle-service/src/components/Planning/TeamCard/TeamCard.tsx
![스크린샷 2024-05-14 오전 3 13 46](https://github.com/teamWaggle/Waggle-front/assets/100590110/7a9536dd-dc0a-4c33-aabe-85c7f241fd4f)

시안에는 버튼이 이렇게 나와있는데 어떤게 맞는건가요?

<img width="360" alt="스크린샷 2024-05-14 오전 3 14 16" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/d372a947-b65d-45c4-9308-80b67066e3ee">

2024-05-13 18:42 UTC, sikkzz commented on packages/waggle-service/src/components/Planning/TeamCard/TeamCard.tsx
<img width="345" alt="스크린샷 2024-05-14 오전 3 15 18" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/1fa7b55d-62ba-4682-96bc-53bf035d1061">

달력 클릭시 key 에러 수정 부탁드려요

2024-05-13 18:42 UTC, sikkzz commented on packages/waggle-service/src/components/Planning/TeamCard/TeamCard.tsx
![스크린샷 2024-05-14 오전 3 15 59](https://github.com/teamWaggle/Waggle-front/assets/100590110/c334bf05-549d-4c30-9036-d91e26e04e4e)

이거도 시안하고 안맞네요

<img width="352" alt="스크린샷 2024-05-14 오전 3 15 57" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/188b5ac4-1268-427e-a2fd-010a0b61772f">

2024-05-13 18:42 UTC, sikkzz commented on packages/waggle-service/src/components/Team/TeamSchedule/Modal/AddTeamScheduleModal.tsx
<img width="686" alt="스크린샷 2024-05-14 오전 3 19 03" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/3df15a52-6d99-4923-979d-11afc08f035b">

소통해서 시안이랑 디자인 맞춰야 하지 않을까요? 글자 크기, input 내부 글자 크기 등이 시안과 다르고 일정 설명 input 위치 조정도 필요해 보이네요

![스크린샷 2024-05-14 오전 3 19 00](https://github.com/teamWaggle/Waggle-front/assets/100590110/f4761af6-1ed4-4ca4-a9f6-73d9258aa86b)

2024-05-13 18:42 UTC, sikkzz commented on packages/waggle-service/src/components/Planning/TeamCard/TeamCard.tsx
<img width="566" alt="스크린샷 2024-05-14 오전 3 20 59" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/21d48c63-15b6-4df8-a312-841c69df7b65">

여기도 input 내부 폰트 조정 필요해 보이네요. placeholder도 같이요

그리고 이미지값이 안들어오네요 수정에서도

2024-05-13 18:42 UTC, sikkzz commented on packages/waggle-service/src/components/Planning/TeamCard/TeamCard.tsx
![스크린샷 2024-05-14 오전 3 22 59](https://github.com/teamWaggle/Waggle-front/assets/100590110/661612cb-cbd8-49ad-aeb9-aeee7497087c)

시안에서 팀 삭제하기 버튼은 여기 있네요 그리고 팀 수정하기 버튼 시안과 폰트가 달라보입니다

<img width="140" alt="스크린샷 2024-05-14 오전 3 23 29" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/8375ada3-b41f-4068-8132-239259c3c95c">

2024-05-13 18:42 UTC, sikkzz commented on packages/waggle-service/src/components/Team/TeamSchedule/TeamSchedule.tsx
<img width="398" alt="스크린샷 2024-05-14 오전 3 26 04" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/5c6e6a8c-2d0b-4af3-aaaa-471c95217b3c">

예정 버튼 컬러 안들어갔네요

2024-05-13 18:42 UTC, sikkzz commented on packages/waggle-service/src/components/Team/TeamSchedule/TeamSchedule.tsx
<img width="413" alt="스크린샷 2024-05-14 오전 3 27 26" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/957c3367-fb85-4749-b887-e34f7426bd22">

현재 시간 5월 14일 3시 27분인데 5월 14일 12시부터 12시 15분 일정이 추가가 되네요. 이전 시간 일정은 추가가 불가능하게 validate 필요해보입니다. 그리고 만약 저게 존재했던 일정이면 마감 처리가 되어야 하지 않을까요?

2024-05-13 18:42 UTC, sikkzz commented on packages/waggle-service/src/components/Team/TeamSchedule/TeamSchedule.tsx
<img width="794" alt="스크린샷 2024-05-14 오전 3 29 07" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/500467e9-ecb3-4722-a277-234bfccb4d81">

1. 본인이 생성한 일정은 무조건 본인 일정에 추가되는건가요? 그렇다면 내 일정에 추가 버튼에 뭔가 다른 표시나 변화가 있어야 하지 않을까요? 
2. 겹치는 일정 처리도 안되는거 같네요 확인 부탁드려요

2024-05-13 18:42 UTC, sikkzz commented on packages/waggle-service/src/components/Team/TeamSchedule/TeamSchedule.tsx
<img width="1207" alt="스크린샷 2024-05-14 오전 3 31 24" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/37143538-afe1-4a55-958a-e1cdf915e1b3">

18일 부터 18일 일정을 검색했는데 17일 일정들이 검색되네요? 이건 왜이러는지 아시나요

2024-05-13 18:42 UTC, sikkzz commented on packages/waggle-service/src/components/Planning/Main/Main.tsx
<img width="1209" alt="스크린샷 2024-05-14 오전 3 33 08" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/a3fd499c-d4f4-41fd-8993-ca8d6c93ad2e">

여기는 아직 전체 팀 조회가 구현이 안된건가요?

2024-05-13 18:42 UTC, sikkzz commented on packages/waggle-service/src/components/Planning/Calendar/CalendarCard/ScheduleModal/ScheduleModal.tsx
<img width="643" alt="스크린샷 2024-05-14 오전 3 37 56" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/b496885a-db7b-493a-844b-bfb2fa6e203f">

1. 댓글이 없을 경우 레이아웃 어떻게 할지 결정 필요
2. 기본 height가 너무 큰거 아닌가요? 요소가 없을때도 크니까 너무 비어 보이네요
3. 분 단위를 표시 안해줘도 될까요? 오전 12시부터 오전 12시로 표시되니까 어색해서요
4. 일정 물결 사이 공백 확인해주세요

2024-05-13 18:42 UTC, sikkzz commented on packages/waggle-service/src/components/Planning/Calendar/CalendarCard/ScheduleModal/ScheduleModal.tsx
<img width="657" alt="스크린샷 2024-05-14 오전 3 40 17" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/e017389b-09db-48fa-b89b-f79bb07e824b">

useOutsideClick 작동이 이상한거 같네요 일정 클릭시 껏다 켜졌다 해야하는데 꺼지지가 않네요

2024-05-13 18:42 UTC, sikkzz commented on packages/waggle-service/src/components/Planning/Calendar/CalendarCard/ScheduleModal/ScheduleModal.tsx
<img width="519" alt="스크린샷 2024-05-14 오전 3 41 00" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/60ba2d37-7348-41b6-9202-feb922b24c92">

1. 댓글 날짜 세로 가운데 정렬 필요
2. 댓글 contents 시작점이 이상한거 같네요

2024-05-13 18:56 UTC, sikkzz requested changes

2024-05-13 18:56 UTC, sikkzz commented on packages/waggle-service/src/components/Planning/Calendar/CalendarCard/ScheduleModal/CommentField/CommentField.tsx
> +        {commentData?.pages?.map((commentData, page) => (
옵셔널 체이닝 꼭 필요한가요?

2024-05-13 18:56 UTC, sikkzz commented on packages/waggle-service/src/components/Planning/Calendar/CalendarCard/ScheduleModal/CommentField/CommentField.tsx
> +        styles={{ direction: "column", width: "100%", height: "300px", marginTop: "16px" }}
width height는 css로 들어가도 괜찮을거에요

2024-05-13 18:56 UTC, sikkzz commented on packages/waggle-service/src/components/Planning/Main/Main.tsx
> +        {recommendTeamsData?.pages?.map((recommendTeamData, page) => (
여기도 옵셔널 체이닝 필요한건가요?

2024-05-13 18:56 UTC, sikkzz commented on packages/waggle-service/src/components/Planning/Main/Main.tsx
> +        {recommendTeamsData?.pages?.map((recommendTeamData, page) => (
여기 원래 전체 팀리스트 조회가 아니였나요? 추천 팀 조회로 되어있는데 논의해봐야겠네요

2024-05-13 18:56 UTC, sikkzz commented on packages/waggle-service/src/components/Planning/Main/MemberTeamSlider/MemberTeamSlider.tsx
> +  const dataLength = memberTeamsData?.pages[0].result.teamCount;
이게 suspense query 사용을 통해 query 조회 전까지 suspense UI를 보여주기 때문에 옵셔널 체이닝 필요 없이 데이터 조회가 바로 가능한거로 알고 있어요 여기 뿐만아니라 다른곳도 suspenseQuery의 영향이 있다면 옵셔널 체이닝이 필요 없어 보입니다

2024-05-13 18:56 UTC, sikkzz commented on packages/waggle-service/src/components/Planning/Main/MemberTeamSlider/MemberTeamSlider.tsx
> +          {memberTeamsData?.pages.map((memberTeamData) => (
옵셔널

2024-05-13 18:56 UTC, sikkzz commented on packages/waggle-service/src/components/Team/TeamForm/TeamForm.tsx
> +    defaultValues ? editTeamMutate(formData) : createTeamMutate(formData);
여기 미디어 로직 문제가 있어서 이미지가 안뜨는거 같은데 확인해보고 고치시면 console은 다 지워주세요

2024-05-13 18:56 UTC, sikkzz commented on packages/waggle-service/src/components/Team/TeamInfo/TeamInfo.tsx
> +        </AlertModal>
Alery modal도 시안이랑 달라보였어요 확인 부탁드려요

2024-05-13 18:56 UTC, sikkzz commented on packages/waggle-service/src/components/Team/TeamInfo/TeamInfo.tsx
> +              {teamMemberList?.map((member, index) => (
옵셔널

2024-05-13 18:56 UTC, sikkzz commented on packages/waggle-service/src/components/common/AuthorizationContainer/team/TeamMemberAuthorizationContainer.tsx
<img width="1246" alt="스크린샷 2024-05-14 오전 3 52 52" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/ee8066c2-2154-473b-a6a3-ddb6b5be7495">

이 컴포넌트는 TeamInfo에서 한번 쓰이는데 common component로 굳이 빼서 api 호출까지 늘리고 작성할 필요가 있을까요? 겹치는 api들이 양쪽 파일에서 존재하는거 보면 차라리 로직을 조금 수정해서 컴포넌트들 나누던가 하는게 낫지 않을까요

common이지만 하나의 컴포넌트에서밖에 안쓰인다는점, 그런데도 구성을 위해 api 호출이 많다는점을 고려했을때 나눠놓는게 장점으로 와닿지가 않습니다

2024-05-13 18:56 UTC, sikkzz commented on packages/waggle-service/src/components/common/AuthorizationContainer/team/TeamLeaderAuthorizationContainer.tsx
이 컴포넌트도 그렇습니다. 물론 2번 쓰이긴 하지만 컴포넌트로 빼기보다 로직을 차라리 만드는게 나아보여요

2024-05-13 18:58 UTC, sikkzz commented
아직 확인 못한 기능들이 꽤 있어서 우선 이정도만 리뷰 달겠습니다 수정되면 또 볼게요

2024-05-13 19:36 UTC, Hellol77 commented on packages/waggle-service/src/components/common/AuthorizationContainer/team/TeamMemberAuthorizationContainer.tsx
api 호출은 캐싱때문에 한번만 일어납니다. 컴포넌트로 나눈 이유는 teamInfo가 너무 많은 일을 하고 있는 것 같아서 나눠주고 싶었고 명령형보다는 선언형으로 처리해서 깔끔하게 처리하고 싶었어요 common에 넣은 이유는 혹시나 나중에 쓸수 있지 않을까 싶은 마음이었는데 나중에 Team 부분으로만 빼도 될것 같습니다.

2024-05-13 19:38 UTC, Hellol77 commented on packages/waggle-service/src/components/Team/TeamForm/TeamForm.tsx
> +    defaultValues ? editTeamMutate(formData) : createTeamMutate(formData);
현재 모든 미디어 로직 관련 (팀 이미지나 멤버 이미지 출력)은 제대로 api가 동작을 안하는 것 같아서 추후에 다시 해야할 것 같아요

2024-05-13 19:40 UTC, Hellol77 commented on packages/waggle-service/src/components/Planning/Main/Main.tsx
> +        {recommendTeamsData?.pages?.map((recommendTeamData, page) => (
현재 전체 팀 리스트 조회가 없어서 일단 넣었습니다

2024-05-13 19:55 UTC, Hellol77 commented on packages/waggle-service/src/components/Team/TeamInfo/TeamInfo.tsx
> +        </AlertModal>
이건 예빈님한테 한번 여쭤볼게요

2024-05-13 19:59 UTC, Hellol77 commented on packages/waggle-service/src/components/Team/TeamSchedule/TeamSchedule.tsx
이건 벡엔드 일정 검색 api 로직상 일정이 18일에도 있기때문에 같이 검색되는 것 같네요

2024-05-13 19:59 UTC, Hellol77 commented on packages/waggle-service/src/components/Planning/TeamCard/TeamCard.tsx
이것도 미디어 쿼리 해결하고 다시 할게요

2024-05-13 20:00 UTC, Hellol77 commented on packages/waggle-service/src/components/Planning/TeamCard/TeamCard.tsx
이것도 미디어 쿼리 해결하고 다시 할게요

2024-05-13 20:02 UTC, Hellol77 commented on packages/waggle-service/src/api/interceptors.ts
> +  console.log(error);
넵 일단 이거 있어야 할 것 같습니다. 가끔씩 console에서 에러 이유를 알수가 없더군요. 여기서 처리해야 error.detail 까지 볼 수 있어서 일단 놔둬야 할것 같습니다.

2024-05-13 20:18 UTC, Hellol77 commented on packages/waggle-service/src/api/comment/putComment.ts
> +  return authorizedAxiosInstance.put<CommentApiRequestType, AxiosResponse<CommonResponseType>>(
EditCommentPropsType은 commentId도 포함되어 있는 타입이라 body에는 content만 들어가서 따로 정의 해줬습니다.
근데 그걸 제외하고 봐도 타입이 잘못 됬네요
```js
return authorizedAxiosInstance.put<
    CommonResponseType,
    AxiosResponse<CommonResponseType>,
    CommentApiRequestType
  >(END_POINTS.COMMENT(commentId), {
    content,
  });
```
이렇게 써야하네요

2024-05-13 20:19 UTC, Hellol77 commented on packages/waggle-service/src/api/comment/postComment.ts
> +    CommentApiRequestType,
아래와 같습니다

2024-05-13 20:21 UTC, Hellol77 commented on packages/waggle-service/src/components/Planning/Main/Main.tsx
현재 전체 팀 리스트 조회가 없어서 일단 Recommend 넣었습니다
보니까 팀 검색이 안들어갔네요.. 이것도 추후에 추가할게요

2024-05-13 20:23 UTC, Hellol77 commented on packages/waggle-service/src/components/Planning/Calendar/CalendarCard/ScheduleModal/ScheduleModal.tsx
저는 일단 잘 동작하는데 어디가 문제인지 자세히 말씀해주시겠어요?

2024-05-13 20:28 UTC, Hellol77 commented on packages/waggle-service/src/components/Planning/TeamCard/TeamCard.tsx
일단 본인은 버튼이 안나오게 설정했습니다

2024-05-13 20:38 UTC, Hellol77 commented on packages/waggle-service/src/components/Team/TeamSchedule/Modal/AddTeamScheduleModal.tsx
이건 저번 회의 때 시작시간 종료시간 나눠서 하자고 한 뒤로 디자인은 변경이 없길래 일단 완성만 해놨습니다. 회의때 얘기를 해봐야겠네요

2024-05-13 20:42 UTC, Hellol77 commented on packages/waggle-service/src/components/Planning/TeamCard/TeamCard.tsx
이것도 미디어 쿼리 해결 후 진행할게요

2024-05-13 20:44 UTC, Hellol77 commented on packages/waggle-service/src/components/Team/TeamSchedule/TeamSchedule.tsx
이거 저번에 회의때 말씀 드렸는데 이건 일단 이대로 해야할 것 같아요 유효성 검사가 꽤나 복잡해지고 마음대로 동작을 안해서 일단 이대로 가야할 것 같습니다

2024-05-13 20:45 UTC, Hellol77 commented on packages/waggle-service/src/components/Team/TeamSchedule/TeamSchedule.tsx
맞아요 처리 해줘야 될것 같습니다.
겹치는 일정 추가할게요

2024-05-22 14:25 UTC, sikkzz commented on packages/waggle-service/src/components/Planning/TeamCard/TeamCard.tsx
이미지 크기 밀리는거 수정

2024-05-22 14:29 UTC, sikkzz commented on packages/waggle-service/src/components/Team/TeamSchedule/Modal/AddTeamScheduleModal.tsx
재수정

2024-05-22 14:29 UTC, sikkzz commented on packages/waggle-service/src/components/Planning/TeamCard/TeamCard.tsx
재수정

2024-06-05 11:58 UTC, sikkzz commented on packages/waggle-service/src/components/Planning/TeamCard/TeamCard.tsx
팀 소개 textarea font 아직도 수정 안된거 같네요

2024-06-05 11:59 UTC, sikkzz commented on packages/waggle-service/src/components/Planning/TeamCard/TeamCard.tsx
폰트 여전히 달라요

2024-06-05 12:00 UTC, sikkzz commented
다시 테스트 돌려보려하는데 팀생성 기능이 안돌아가네요 확인좀 부탁드려요

2024-06-08 14:15 UTC, sikkzz requested changes

2024-06-08 14:15 UTC, sikkzz commented on packages/waggle-service/src/components/Team/TeamForm/TeamForm.tsx
<img width="1268" alt="스크린샷 2024-06-08 오후 10 53 24" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/5e2d3899-c859-4b29-b511-d01b179710c3">

팀 생성하기때는 설정하기가 아니라 생성하기가 맞지 않을까요?

2024-06-08 14:15 UTC, sikkzz commented on packages/waggle-service/src/components/Team/TeamSchedule/Modal/AddTeamScheduleModal.tsx
<img width="494" alt="스크린샷 2024-06-08 오후 10 57 48" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/f00a80c1-af34-4d5c-b560-d9b5c0dff910">

이거 일정 추가 버튼 팀 컬러에 따라 달라지는건지 이 컬러로 고정인지 한번만 물어봐주실래요?

2024-06-08 14:15 UTC, sikkzz commented on packages/waggle-service/src/components/Team/TeamSchedule/TeamSchedule.tsx
<img width="398" alt="스크린샷 2024-06-08 오후 11 00 05" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/de9dc19d-3fea-4012-b4e9-414172b69012">

지금 6월 8일 오후 11시에 생성한 일정인데 진행중으로 뜨네요? 확인 한번 해주세요

2024-06-08 14:15 UTC, sikkzz commented on packages/waggle-service/src/pages/TeamPage.tsx
<img width="1151" alt="스크린샷 2024-06-08 오후 11 03 16" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/9cf742b2-5783-4424-918c-dcb76f2e65f1">

여기 전체 팀 목록 조회 api는 언제 만들어지는걸까요? 계속 추천 팀 목록 조회 api네요

2024-06-08 14:15 UTC, sikkzz commented on packages/waggle-service/src/components/Team/TeamSchedule/TeamSchedule.tsx
<img width="411" alt="스크린샷 2024-06-08 오후 11 11 12" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/042f6a7c-1386-494d-8dff-75eaad297e1d">

겹치는 일정이 없을 때 호버하면 빈 div랑 화살표가 뜨네요 없을때는 안떠야 할 거 같아요

2024-06-08 14:15 UTC, sikkzz commented on packages/waggle-service/src/components/Planning/Calendar/CalendarCard/ScheduleModal/ScheduleModal.tsx
<img width="502" alt="스크린샷 2024-06-08 오후 11 12 20" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/bb1276a7-24be-42f2-97f8-cd8b46992620">

일정 참여 취소를 했을 때 겹치는 일정 및 내 일정에 추가 버튼이 다시 렌더링되어야하는데 바로 렌더링이 안뜨네요

2024-06-08 14:20 UTC, sikkzz requested changes

2024-06-08 14:20 UTC, sikkzz commented on packages/waggle-design-system/package.json
![스크린샷 2024-06-08 오후 11 17 39](https://github.com/teamWaggle/Waggle-front/assets/100590110/042f381d-fc39-4816-897a-cadc286b3372)

검색 날짜가 이상할때도 toast 에러메시지 하나 있으면 좋지 않을까요? 일정 생성할때는 저렇게 안내문구가 있긴하니까요

![스크린샷 2024-06-08 오후 11 19 25](https://github.com/teamWaggle/Waggle-front/assets/100590110/083a76d6-7eb4-4cea-b052-1b22fb28f155)

2024-06-08 14:20 UTC, sikkzz commented on packages/waggle-design-system/package.json
한번 팀에서 멤버가 삭제되고 재가입하려하면 이미 존재하는 요청이라는 에러메시지가 뜨는데 이건 백엔드 로직에서 일주일뒤 신청 로직이 있어서 그런건가요?

2024-06-08 14:22 UTC, sikkzz commented on packages/waggle-service/src/components/Planning/Calendar/CalendarCard/ScheduleModal/ScheduleModal.tsx
<img width="477" alt="스크린샷 2024-06-08 오후 11 22 06" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/581f7c51-e07e-4457-97f7-de1a785899d0">

월과 일사이에 공백 하나만 있으면 될 거 같아요!

2024-06-08 14:33 UTC, Hellol77 commented on packages/waggle-service/src/pages/TeamPage.tsx
전체 팀 목록조회는 현재 없어서 일단은 팀 추천 목록으로 유지해야할 것 같아요

2024-06-08 14:37 UTC, Hellol77 commented on packages/waggle-design-system/package.json
넵 맞습니다

2024-06-08 14:38 UTC, Hellol77 commented on packages/waggle-service/src/pages/TeamPage.tsx
이건 벡엔드에서 만들어줘야 될 것 같아요 그 전까지는 이렇게 유지밖에 답이 없네요

2024-06-08 15:04 UTC, Hellol77 commented on packages/waggle-service/src/pages/TeamPage.tsx
그리고 일정 추가 버튼은 바뀌는 게 맞습니다

2024-06-08 15:20 UTC, Hellol77 commented on packages/waggle-design-system/package.json
toast 메시지로 추가했습니다

2024-06-09 05:00 UTC, sikkzz commented on packages/waggle-service/src/components/Team/TeamForm/TeamForm.tsx
이거 최상단 타이틀도 바꿔주는게 맞을 거 같아요

2024-06-12 12:27 UTC, sikkzz approved these changes

2024-06-12 12:31 UTC, merged