55 create planning main page, slider
teamWaggle/Waggle-front pull request #60
Opened 2024-02-08 11:17 UTC by Hellol77

# 설명
- [https://github.com/teamWaggle/Waggle-front/issues/55](https://github.com/teamWaggle/Waggle-front/issues/55)

# 미구현 기능
- search 기능
- 팀만들기
- team card 클릭 시 페이지 이동
- calendar 일정 클릭 시 modal

- 특이사항은 없는것 같아요

2024-02-09 11:46 UTC, sikkzz requested changes

2024-02-09 11:46 UTC, sikkzz commented on src/components/Planning/TeamCard/TeamCard.tsx
![스크린샷 2024-02-09 오후 8 34 44](https://github.com/teamWaggle/Waggle-front/assets/100590110/55e037c2-1dbb-40d7-88af-d8fd5e4b52f3)

height값을 고정할 때 디자인 시안은 본문 텍스트가 2줄인데 여기는 1줄이라 아래 공간에 여백이 생기네요. 본문 영역 height 고정시키고 인원수 text를 아래쪽으로 내리면 좋을 거 같아요

2024-02-09 11:46 UTC, sikkzz commented on src/components/Planning/Main/Main.tsx
> +				{mockData.map((data, index) => (
index 없이 key 값은 data.title이나 id값으로 사용해도 되지 않을까요? 나중에 api 연결할때 id값이 넘어올지는 모르겠지만요

2024-02-09 11:46 UTC, sikkzz commented on src/components/Planning/Main/Slider/Slider.tsx
> +		return;
return 지워도 되지 않을까요?

2024-02-09 11:46 UTC, sikkzz commented on src/components/Planning/Main/Slider/Slider.tsx
> +	const handleNext = () => {
handlePrevClick 이나 handlePrevButtonClick 같이 좀 더 자세하게 네이밍 하면 좋을 거 같아요

2024-02-09 11:46 UTC, sikkzz commented on src/components/Planning/TeamCard/TeamCard.style.ts
> +	borderColor: Theme.color.brand_primary,
border: `2px solid ${Theme.color.brand_primary}` 이렇게 스타일링 가능해요

2024-02-09 11:46 UTC, sikkzz commented on src/components/Planning/TeamCard/TeamCard.style.ts
> +	padding: "8px 16px 0px 16px",
padding: "8px 16px 0" 이랑 동일한 코드 같네요

2024-02-09 11:46 UTC, sikkzz commented on src/components/Planning/TeamCard/TeamCard.tsx
> +			<img src={photoUrl} alt="" css={imgStyle} />
alt명 빼놓은 이유가 있을까요?

2024-02-09 11:46 UTC, sikkzz commented on src/components/Planning/TeamCard/TeamCard.tsx
> +				<Text size="small" css={subtitleTextStyle} style={{ marginBottom: "8px" }}>
css 파일이 있는데 인라인 스타일을 쓸 이유가 없지 않을까요

2024-02-09 11:46 UTC, sikkzz commented on src/components/Planning/TeamCard/TeamCard.tsx
> +						{groupSize}/50
그룹 최대 인원수도 data값으로 넘어올 예정이면 data화 하는게 나을 거 같아요

2024-02-09 11:46 UTC, sikkzz commented on src/components/Planning/TeamCard/TeamCard.style.ts
> +		marginBottom: "4px",
이 margin값 때문에 세로 중앙 정렬이 안맞네요

![스크린샷 2024-02-09 오후 8 43 34](https://github.com/teamWaggle/Waggle-front/assets/100590110/21bcfd0a-2e15-4156-9c8f-405261b3a6be)

2024-02-09 11:46 UTC, sikkzz commented on src/components/Planning/TeamCard/TeamCard.tsx
> +					&nbsp;
&nbsp 제거하고 위에 Flex tag에서 gap 주면 될 거 같아요

2024-02-09 11:46 UTC, sikkzz commented on src/components/Planning/TeamCard/TeamCard.tsx
> +				<Flex style={{ alignItems: "center" }}>
여기서 gap 주면 되고 style prop은 그냥 인라인 스타일링이에요. 컴포넌트에 지정된 스타일링 쓰려면 styles prop을 사용해야 합니다

2024-02-09 11:46 UTC, sikkzz commented on src/components/common/SearchInput/SearchInput.tsx
이건 이전에 말씀드렸듯 제가 만들어놓은 search bar가 있긴한데 머지하고 이후에 공통으로 뺄 수 있는지 확인해볼게요. 당장은 리뷰 안할게요

2024-02-11 08:44 UTC, sikkzz commented on src/components/Planning/TeamCard/TeamCard.tsx
> +				<Flex style={{ alignItems: "center" }}>
<Flex styles={{align: "center", gap: "4px", marginBottom: "4px"}}> 

prop명 이거 얘기한거에요. styles로 사용해야 미리 선언해놓은 styling 사용 가능해요

<img width="916" alt="스크린샷 2024-02-11 오후 5 43 52" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/6d7fa8bc-1b2e-45cc-89df-576d34036a78">

2024-02-11 10:19 UTC, Hellol77 commented on src/components/Planning/TeamCard/TeamCard.tsx
> +				<Flex style={{ alignItems: "center" }}>
아아 이해했습니다~

2024-02-11 10:28 UTC, sikkzz approved these changes

2024-02-11 10:41 UTC, merged