64 front task create a modal in planning page
teamWaggle/Waggle-front pull request #79
Opened 2024-02-17 20:59 UTC by Hellol77

# 설명

- [https://github.com/teamWaggle/Waggle-front/issues/64](https://github.com/teamWaggle/Waggle-front/issues/64)
- recoil에 schedule modal 추가
- App.tsx 에 routes 상수화
- Schedule Modal , More Modal 추가
# 특이사항
- Schedule modal은 위치가 정해져있는 기존 모달과는 달리 위치가 달라지는 모달이라 ModalRoot에 새로 만들었습니다.
- App.tsx에 Route들을 상수화해서 관리하면 편할 수도 있을것 같아서 변경해보았습니다. (예를 들면 로그인 한 상태에서만 접근 가능한 Route들을 쉽게 나눌수 있는 점)
- Schedule , More Modal에 ref를 사용하기 위해 section 태그를 사용했습니다. 기존 common 컴포넌트는 forwardRef로 만들어지지 않아ref를 전달 할 수 없어서 새로 컴포넌트를 만들까 하다가 일단 section 태그를 사용했습니다. (기존 common 컴포넌트를 forwardRef로 교체하고 진행하려 했으나 forwardRef를 쓰면 무조건 ref를 전달해야 되더군요. 유명 Ui 라이브러리를 뒤져보면 해결책을 찾을 수 있을 것 같기도 한데 일단 진행했어요)

2024-02-18 07:18 UTC, sikkzz requested changes

2024-02-18 07:18 UTC, sikkzz commented on src/api/index.d.ts
불필요 파일인데 들어가있네요 삭제하셔도 됩니다

2024-02-18 07:18 UTC, sikkzz commented on src/components/Planning/Calendar/Calendar.tsx
>  import { ScheduleType } from "@/types/planning";
import type 붙여주세요! 그럼 import order 적용해서 줄바꿈도 될 거에요

2024-02-18 07:18 UTC, sikkzz commented on src/components/Planning/Calendar/CalendarCard/CalendarCard.tsx
> +import { CalendarCardType, ScheduleType } from "@/types/planning";
import type

2024-02-18 07:18 UTC, sikkzz commented on src/components/Planning/Calendar/CalendarCard/CalendarCard.tsx
> +					<Fragment key={schedule.scheduleId + dayString}>
여기 Fragement가 꼭 필요한건가요? 아래 Box 태그로도 감싸지는거 같은데 추가하신 이유가 있을꺄요?

2024-02-18 07:18 UTC, sikkzz commented on src/components/Planning/Calendar/CalendarCard/CalendarCard.tsx
> +					<>
여기도 위랑 동일하게 빈 태그 하나 들어간 이유가 있나요?

2024-02-18 07:18 UTC, sikkzz commented on src/components/Planning/Calendar/CalendarCard/MoreModal/MoreModal.tsx
> +import { ScheduleType } from "@/types/planning";
import type

2024-02-18 07:18 UTC, sikkzz commented on src/components/Planning/Calendar/CalendarCard/ScheduleModal/Comment/Comment.tsx
> +				<img css={imgStyle} src="https://source.unsplash.com/random/300x300" alt="" />
alt값

2024-02-18 07:18 UTC, sikkzz commented on src/components/Planning/Calendar/CalendarCard/ScheduleModal/Comment/Comment.tsx
> +						<Text size="medium" css={commentUserNameStyle}>
medium이 default라 medium때는 선언 안해주셔도 됩니당

2024-02-18 07:18 UTC, sikkzz commented on src/components/Planning/Calendar/CalendarCard/ScheduleModal/ScheduleModal.tsx
> +import { ScheduleModalType } from "@/types/modal";
import type

2024-02-18 07:18 UTC, sikkzz commented on src/components/Planning/Calendar/CalendarHeader/CalendarHeader.tsx
> +		<Flex tag={"section"} css={flexStyle}>
tag들 중괄호 없이 그냥 "section"으로 사용해도 됩니다. 이거 코드 전체 한번 확인 부탁드려요!

2024-02-18 07:18 UTC, sikkzz commented on src/components/common/Text/MentionChecker/MentionChecker.style.ts
> +	// width: "fit-content",	fontSize: "12px",
불필요한 주석이면 지워도 되겠네요

2024-02-18 07:22 UTC, sikkzz commented
캘린더에서 일정 클릭시 뜨는 모달이 가운데 기준 왼쪽에 있는 일정들은 정상적으로 뜨는데 오른쪽에 있는 모달들은 뜨는게 이상하네요? 확인 한번 부탁드려요 아래 영상 첨부해드려요

https://github.com/teamWaggle/Waggle-front/assets/100590110/8bafa2ce-7dca-48b1-8c18-c410fa0a5a39

2024-02-18 09:14 UTC, Hellol77 commented on src/components/Planning/Calendar/CalendarCard/ScheduleModal/Comment/Comment.tsx
> +				<img css={imgStyle} src="https://source.unsplash.com/random/300x300" alt="" />
이건 데이터 가져올때 그때 하겠습니당

2024-02-18 09:20 UTC, Hellol77 commented
> 캘린더에서 일정 클릭시 뜨는 모달이 가운데 기준 왼쪽에 있는 일정들은 정상적으로 뜨는데 오른쪽에 있는 모달들은 뜨는게 이상하네요? 확인 한번 부탁드려요 아래 영상 첨부해드려요
> 
>  2024-02-18.4.21.18.mov

2024-02-18 09:56 UTC, sikkzz requested changes

2024-02-18 09:56 UTC, sikkzz commented on src/components/Planning/Calendar/CalendarCard/MoreModal/MoreModal.tsx
> +import { type ScheduleType } from "@/types/planning";
잘못 추가하신거 같아요 앞으로 빼야하는데

2024-02-18 09:57 UTC, sikkzz commented
> > 캘린더에서 일정 클릭시 뜨는 모달이 가운데 기준 왼쪽에 있는 일정들은 정상적으로 뜨는데 오른쪽에 있는 모달들은 뜨는게 이상하네요? 확인 한번 부탁드려요 아래 영상 첨부해드려요
> > 2024-02-18.4.21.18.mov
> 
> 요 문제는 ModalRoot를 Calendar로 바꾸는 것으로 해결했습니다

이부분은 확인했습니다~

2024-02-18 09:58 UTC, sikkzz commented
추가적으로 의견인데 일정 클릭시 해당 일정이 클릭된거라는 인터렉션이 뭔가 추가되면 어떨까요? 들어가면 좋을 거 같아서요 해당 기능은 추가하실꺼면 디자이너분이랑 얘기해보시면 좋을 거 같아요! 이 브랜치 리뷰사항으로 포함시키지는 않을게요

<img width="678" alt="스크린샷 2024-02-18 오후 6 57 25" src="https://github.com/teamWaggle/Waggle-front/assets/100590110/fda1cf3b-3d10-407d-948a-9aff6b1ef053">

2024-02-19 06:05 UTC, sikkzz approved these changes

2024-02-19 11:14 UTC, merged